### ISSUE TITLE
Musics not changing when normal music fades.

### ISSUE THREAD

**Issue by ZonihaDarkness** [lmcintyre/OrchestrionPlugin#4]
Since the update for 6.0 whenever the previous song of a area should stop playing it keeps up with it. Examples as follow:

-At Seat of Sacrifice normal mode. Both when the active time maneuver and the phase 2 cutscene starts "To the Edge" keeps playing uninterruptedly.

-Some La Noscean areas when at night, when mounted it keeps playing the mount music even with mount BGM turned off (e.g. leaving Mist at night to Lower La Noscea). If not mounted it keeps playing the previous area music (Limsa or Mist for example).

-Any cutscene when watching from the Unending Journey at the Inn keeps playing "Behind Closed Doors".

-Alexander: The Soul of Creator should stop playing "Mobius" during phase transition but it keeps going until "Rise" starts playing.

**Comment by lmcintyre** [comment]
I have not had any further reports of any of this behavior, especially since the discovery that disabling audio streaming causes numerous issues and telling users to turn audio streaming back on (disabling the disable of audio streaming). Closing this and discussion can continue in a new issue if there are problems.
