### ISSUE TITLE
[Feature request] Extract music as MP3/OGG

### ISSUE THREAD

**Issue by Flavescent** [lmcintyre/OrchestrionPlugin#44]
Hi, thank you very much for making this plugin! Since it allows direct access to game music, could you provide a function to save songs or playlists as media files to local storage, such as OGG, MP3 or whatever the music's format is? This would be easier than to have to record the audio output for home listening.

**Comment by lmcintyre** [comment]
There are many other tools to extract sound and music, including (I believe) the VFXEditor plugin. In addition, the audio from the game is extremely low quality compared to the soundtrack releases. If possible, I would recommend obtaining the soundtracks for home listening rather than extracting from the game. I will not be adding this to Orchestrion.
